---
development:
  cloud_name: zmsh-herokuapp-com
  api_key: '879333924183535'
  api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: zmsh-herokuapp-com
  api_key: '879333924183535'
  api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: zmsh-herokuapp-com
  api_key: '879333924183535'
  api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  enhance_image_tag: true
  static_image_support: false
